#nullable enable

// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// Validation helpers for CacheService to ensure data integrity and prevent runtime errors
// =============================================================================

using System;
using System.Collections.Generic;
using System.Linq;

namespace JobScheduler.Core.Services;

/// <summary>
/// Provides validation helpers for <see cref="CacheService"/> instances.
/// Ensures cache keys, values, and configuration are valid before operations.
/// </summary>
public static class CacheServiceValidation
{
    /// <summary>
    /// Validates a <see cref="CacheService"/> instance for common issues.
    /// </summary>
    /// <param name="value">The CacheService instance to validate.</param>
    /// <returns>A list of human-readable validation problems, or empty if valid.</returns>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is null.</exception>
    public static IReadOnlyList<string> Validate(this CacheService? value)
    {
        ArgumentNullException.ThrowIfNull(value);

        var problems = new List<string>();

        // CacheService itself has no public properties to validate beyond its constructor dependencies
        // which are validated in the constructor itself

        return problems.AsReadOnly();
    }

    /// <summary>
    /// Determines whether a <see cref="CacheService"/> instance is valid.
    /// </summary>
    /// <param name="value">The CacheService instance to check.</param>
    /// <returns>True if the instance is valid; otherwise, false.</returns>
    public static bool IsValid(this CacheService? value) => value is not null && !value.Validate().Any();

    /// <summary>
    /// Ensures that a <see cref="CacheService"/> instance is valid, throwing an exception if not.
    /// </summary>
    /// <param name="value">The CacheService instance to validate.</param>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="value"/> is null.</exception>
    /// <exception cref="ArgumentException">Thrown if <paramref name="value"/> has validation problems.</exception>
    public static void EnsureValid(this CacheService? value)
    {
        ArgumentNullException.ThrowIfNull(value);

        var problems = value.Validate();

        if (problems.Count == 0)
            return;

        throw new ArgumentException(
            $"CacheService validation failed:{Environment.NewLine}{string.Join(Environment.NewLine, problems)}");
    }

    /// <summary>
    /// Validates cache keys generated by CacheKeyGenerator.
    /// </summary>
    /// <param name="key">The cache key to validate.</param>
    /// <returns>A list of human-readable validation problems, or empty if valid.</returns>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="key"/> is null.</exception>
    /// <exception cref="ArgumentException">Thrown if <paramref name="key"/> is empty or contains invalid characters.</exception>
    public static IReadOnlyList<string> ValidateKey(string? key)
    {
        ArgumentException.ThrowIfNullOrEmpty(key);

        var problems = new List<string>();

        if (string.IsNullOrWhiteSpace(key))
        {
            problems.Add("Cache key cannot be whitespace or empty.");
        }

        if (key.Length > 1024)
        {
            problems.Add("Cache key cannot exceed 1024 characters.");
        }

        if (key.Contains(' ') || key.Contains('\t') || key.Contains('\n') || key.Contains('\r'))
        {
            problems.Add("Cache key cannot contain whitespace characters.");
        }

        if (!key.All(c => c is >= ' ' and <= '~'))
        {
            problems.Add("Cache key can only contain ASCII printable characters.");
        }

        return problems.AsReadOnly();
    }

    /// <summary>
    /// Determines whether a cache key is valid.
    /// </summary>
    /// <param name="key">The cache key to check.</param>
    /// <returns>True if the key is valid; otherwise, false.</returns>
    public static bool IsValidKey(string? key) => key is not null && !ValidateKey(key).Any();

    /// <summary>
    /// Ensures that a cache key is valid, throwing an exception if not.
    /// </summary>
    /// <param name="key">The cache key to validate.</param>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="key"/> is null.</exception>
    /// <exception cref="ArgumentException">Thrown if <paramref name="key"/> has validation problems.</exception>
    public static void EnsureValidKey(string? key)
    {
        ArgumentException.ThrowIfNullOrEmpty(key);

        var problems = ValidateKey(key);

        if (problems.Count > 0)
        {
            throw new ArgumentException(
                $"Cache key validation failed: {string.Join(" ", problems)}");
        }
    }

    /// <summary>
    /// Validates cache key patterns used in invalidation operations.
    /// </summary>
    /// <param name="keyPattern">The cache key pattern to validate.</param>
    /// <returns>A list of human-readable validation problems, or empty if valid.</returns>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="keyPattern"/> is null.</exception>
    /// <exception cref="ArgumentException">Thrown if <paramref name="keyPattern"/> is empty.</exception>
    public static IReadOnlyList<string> ValidateKeyPattern(string? keyPattern)
    {
        ArgumentException.ThrowIfNullOrEmpty(keyPattern);

        var problems = new List<string>();

        if (string.IsNullOrWhiteSpace(keyPattern))
        {
            problems.Add("Cache key pattern cannot be whitespace or empty.");
        }

        if (keyPattern.Length > 1024)
        {
            problems.Add("Cache key pattern cannot exceed 1024 characters.");
        }

        // Pattern should not be a complete key (patterns typically contain wildcards)
        if (!keyPattern.Contains('*') && !keyPattern.Contains('?'))
        {
            problems.Add("Cache key pattern should contain wildcards (* or ?) for pattern matching.");
        }

        return problems.AsReadOnly();
    }

    /// <summary>
    /// Determines whether a cache key pattern is valid.
    /// </summary>
    /// <param name="keyPattern">The cache key pattern to check.</param>
    /// <returns>True if the pattern is valid; otherwise, false.</returns>
    public static bool IsValidKeyPattern(string? keyPattern) => keyPattern is not null && !ValidateKeyPattern(keyPattern).Any();

    /// <summary>
    /// Ensures that a cache key pattern is valid, throwing an exception if not.
    /// </summary>
    /// <param name="keyPattern">The cache key pattern to validate.</param>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="keyPattern"/> is null.</exception>
    /// <exception cref="ArgumentException">Thrown if <paramref name="keyPattern"/> has validation problems.</exception>
    public static void EnsureValidKeyPattern(string? keyPattern)
    {
        ArgumentException.ThrowIfNullOrEmpty(keyPattern);

        var problems = ValidateKeyPattern(keyPattern);

        if (problems.Count > 0)
        {
            throw new ArgumentException(
                $"Cache key pattern validation failed: {string.Join(" ", problems)}");
        }
    }

    /// <summary>
    /// Validates cache statistics.
    /// </summary>
    /// <param name="statistics">The cache statistics to validate.</param>
    /// <returns>A list of human-readable validation problems, or empty if valid.</returns>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="statistics"/> is null.</exception>
    public static IReadOnlyList<string> Validate(this CacheStatistics? statistics)
    {
        ArgumentNullException.ThrowIfNull(statistics);

        var problems = new List<string>();

        if (statistics.TotalKeys < 0)
        {
            problems.Add("TotalKeys cannot be negative.");
        }

        if (statistics.Timestamp == default)
        {
            problems.Add("Timestamp cannot be default (Unix epoch).");
        }

        if (statistics.Timestamp.Kind != DateTimeKind.Utc)
        {
            problems.Add("Timestamp must be in UTC.");
        }

        if (statistics.Timestamp > DateTime.UtcNow.AddMinutes(5))
        {
            problems.Add("Timestamp cannot be in the future.");
        }

        return problems.AsReadOnly();
    }

    /// <summary>
    /// Determines whether cache statistics are valid.
    /// </summary>
    /// <param name="statistics">The cache statistics to check.</param>
    /// <returns>True if the statistics are valid; otherwise, false.</returns>
    public static bool IsValid(this CacheStatistics? statistics) => statistics is not null && !Validate(statistics).Any();

    /// <summary>
    /// Ensures that cache statistics are valid, throwing an exception if not.
    /// </summary>
    /// <param name="statistics">The cache statistics to validate.</param>
    /// <exception cref="ArgumentNullException">Thrown if <paramref name="statistics"/> is null.</exception>
    /// <exception cref="ArgumentException">Thrown if <paramref name="statistics"/> has validation problems.</exception>
    public static void EnsureValid(this CacheStatistics? statistics)
    {
        ArgumentNullException.ThrowIfNull(statistics);

        var problems = Validate(statistics);

        if (problems.Count > 0)
        {
            throw new ArgumentException(
                $"CacheStatistics validation failed:{Environment.NewLine}{string.Join(Environment.NewLine, problems)}");
        }
    }
}